"""Generated by `hemonc-alchemy regen-classification` on 2026-10-01. Do not hand-edit.

Source: HemOnc extract's local OMOP `Is a` ancestry of each `Drugs.main_class`
value, walked up to two roots -- see `compiler/classification_generation.py`
for the algorithm and the root concept codes/ids/names.

ENDOCRINE_MAIN_CLASSES: every distinct `main_class` value whose components all
resolve (via a real, non-"Steroid" `Is a` chain) to "Endocrine therapeutic"
(concept_id=35807205). Replaces the old, separately
hand-curated GnRH and Hormone buckets: both converge on this single real
ancestor, and HemOnc's own hierarchy has no cut that reproduces the old split.

SUPPORTIVE_MAIN_CLASSES: every distinct `main_class` value whose components all
resolve to "Growth factor" (concept_id=905615).
Narrower than the old hand-curated set: "Somatostatin analog" moved out (it is a
real "Endocrine therapeutic" descendant, not supportive care), and
"IL-1R antagonist"/"Anti-IL-6R antibody" are dropped rather than forced in -- no
principled ancestor covers them without also pulling in real antineoplastics
("Targeted therapeutic") or unrelated immunosuppressants.

`main_class` values with no component resolving to either root (own-name
hierarchy gap in the HemOnc extract, not a classification decision):
# - 'Androgen'
# - 'Anti-LAG-3 antibody'
# - 'Antithrombin siRNA therapeutic'
# - 'Beta blocker'
# - 'Dipeptidyl peptidase-4 inhibitor'
# - 'Estrogen replacement therapy'
# - 'IL-15 receptor alpha fusion protein'
# - 'Quinoline'
# - 'Sulfonamide'

`main_class` values whose components disagree (some but not all resolve to a
root) -- excluded from both sets rather than guessed from a majority:
# - 'Antifungal'
# - 'Granulocyte colony-stimulating factor'
# - 'H2-receptor antagonist'
# - 'Multi-ingredient'
# - 'Radioactive agent'
"""

from __future__ import annotations

ENDOCRINE_MAIN_CLASSES: frozenset[str] = frozenset(
    {
        '5 alpha-reductase inhibitor',
        'Adrenal suppressant',
        'Anabolic steroid',
        'Antiandrogen',
        'Aromatase inhibitor first generation',
        'Aromatase inhibitor second generation',
        'Aromatase inhibitor third generation',
        'CYP17 inhibitor',
        'Estrogen receptor inhibitor',
        'First-generation nonsteroidal antiandrogen',
        'Glucocorticoid receptor antagonist',
        'GnRH agonist',
        'GnRH analog',
        'GnRH antagonist',
        'Progestin',
        'Proteolysis-targeting chimera estrogen receptor degrader',
        'Second-generation nonsteroidal antiandrogen',
        'Selective estrogen receptor modulator',
        'Somatostatin analog',
        'Synthetic steroid',
    }
)

SUPPORTIVE_MAIN_CLASSES: frozenset[str] = frozenset(
    {
        'Erythrocyte growth factor',
        'Keratinocyte growth factor',
        'Megakaryocyte growth factor',
        'TGF-beta inhibitor',
    }
)
